---
title: "Analysis report"
subtitle: " `r Sys.time() ` "
author: "Kazuki Aoyama"
format: 
  html: 
    toc: true
    number-sections: true
    theme: simplex
    backgroundcolor: "#e3e3e3"
    monobackgroundcolor: "#ffffff"
    highlight-style: solarized
    code-block-bg: "#dcd6d2"
    mainfont: Times New Roman, YuMincho, Hiragino Mincho ProN, Yu Mincho,  
              MS PMincho, serif;
    linestretch: "2.5"
    self-contained: true
    code-tools: true
    code-fold: true
    link-external-icon: true
    link-external-newwindow: true
    fig-format: svg
    fig-width: 10
extract-media: "./figures"
bibliography: "./templates/0000_r-project.bib"
csl: "./templates/sage-vancouver.csl"
---

This report contains the analysis code and results for the following research article:

> ....................

# Materials and Methods

## Guidelines

## Data analysis

```{r}
#| label: setup
#| code-fold: false

# set working directory
setwd("~/project/codes")

# change processing of missing values in data frames
options(na.action = "na.pass")

# save default graphics parameters
oldpar <- par(no.readonly = TRUE) 

# attach the package 'checkpoint'
library(checkpoint)

# set checkpoint date
checkpoint("2023-12-1", checkpoint_location = "../", scan_now = FALSE)

# attach packages
# ライブラリの読み込み
library(pacman)

# p_load(caret, randomForest)
install.packages('caret', dependencies=TRUE)
install.packages('randomForest')
library(caret)
library(randomForest)

# データの読み込み
url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
mushroom_data <- read.csv(url, header = FALSE)
colnames(mushroom_data) <- c("class", "cap_shape", "cap_surface", "cap_color", "bruises", "odor", "gill_attachment",
                             "gill_spacing", "gill_size", "gill_color", "stalk_shape", "stalk_root", "stalk_surface_above_ring",
                             "stalk_surface_below_ring", "stalk_color_above_ring", "stalk_color_below_ring", "veil_type",
                             "veil_color", "ring_number", "ring_type", "spore_print_color", "population", "habitat")

# データの分割
set.seed(123)
split_index <- createDataPartition(mushroom_data$class, p = 0.8, list = FALSE)
train_data <- mushroom_data[split_index, ]
test_data <- mushroom_data[-split_index, ]

# LOOCVを含む設定
ctrl_loocv <- trainControl(method = "LOOCV")

# ランダムフォレストモデルのトレーニング
rf_model <- train(class ~ ., data = train_data, method = "rf", trControl = ctrl_loocv)

# 交差検証の結果を表示
print(rf_model)

# テストセットを使用してモデルの性能を評価
predictions <- predict(rf_model, test_data)

# 混同行列の表示
confusion_matrix <- confusionMatrix(predictions, test_data$class)
print(confusion_matrix)

```

```{r}
#| label: terminate

rm(list = ls())

uncheckpoint()

```
